/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Audio configuration */
export interface AudioConfig {
  sampleRate: number
  bufferSize: number
  channels: number
}
/** Pitch detection result */
export interface PitchResult {
  frequency: number
  confidence: number
  algorithm: string
}
/** Auto-tune result */
export interface AutotuneResult {
  originalPitch: number
  correctedPitch: number
  strength: number
  processedSamples: number
}
/** Audio analysis result */
export interface AudioAnalysis {
  pitch: number
  amplitude: number
  qualityScore: number
  features: Array<number>
}
/** Processing options */
export interface ProcessOptions {
  enableAutotune: boolean
  strength: number
  scale: string
  key: string
}
/** Get library version */
export declare function getVersion(): string
/** Initialize the library */
export declare function init(): string
export type MusicAIProcessor = MusicAiProcessor
/** Main MusicAI processor */
export declare class MusicAiProcessor {
  /** Create a new MusicAI processor */
  constructor(config: AudioConfig)
  /** Detect pitch from audio buffer */
  detectPitch(audioBuffer: Float32Array): PitchResult
  /** Apply auto-tune correction */
  applyAutotune(audioBuffer: Float32Array, targetPitch: number, strength: number): Float32Array
  /** Analyze audio buffer */
  analyzeAudio(audioBuffer: Float32Array): AudioAnalysis
  /** Process audio in real-time */
  processRealtime(audioBuffer: Float32Array, options: ProcessOptions): Promise<Float32Array>
}
